name: 🎉 Release

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

on:
  push:
    branches:
      - main

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'moreorover/prive'
    permissions:
      contents: write       # to create release (changesets/action)
      issues: write         # to post issue comments (changesets/action)
      pull-requests: write  # to create pull request (changesets/action)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Create TAG
        id: changesets
        uses: changesets/action@v1
        with:
          version: "pnpm ci:version"
          publish: "pnpm ci:publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure to have this set up under GitHub secrets

      - name: Install Vercel CLI
        if: steps.changesets.outputs.published == 'true'
        run: pnpm i -g vercel@canary

      - name: Setup Supabase CLI
        if: steps.changesets.outputs.published == 'true'
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase CLI to Prod
        if: steps.changesets.outputs.published == 'true'
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Push Supabase DB Changes
        if: steps.changesets.outputs.published == 'true'
        run: supabase db push

      - name: Pull Prod Env Variables
        if: steps.changesets.outputs.published == 'true'
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        if: steps.changesets.outputs.published == 'true'
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        if: steps.changesets.outputs.published == 'true'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN}}
